### ISSUE TITLE
Demo program with Emscripten

### ISSUE THREAD

**Issue by elwongest** [jvanaken1/ShapeGen#1]
Very cool library. SDL2 lacks graphics primitive and although I haven't tried SDL2-gfx, this ShapeGen library looks better featured.

I built it in Webassembly using Emscripten/SDL2. The lib and demo files built without change, although many warnings due to Emscripten's C++11 not happy casting sstring into char*. I had to adapt the sdlmain.cpp to use Emcsripten main loop.  File attached here.
[emscriptenmain.zip](https://github.com/jvanaken1/ShapeGen/files/6327150/emscriptenmain.zip)

I would suggest adding an Emscripten demo program and updating the project page/readme accordingly. It could attract a wider audience to this library. SDL2 is easier for 2D than WebGL.

**Comment by jvanaken1** [comment]
Thanks for the suggestion. I can see how it might be a good addition to this project. I'll look into it.
